export enum BillingEvent {
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  SUBSCRIPTION_CREATED = "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED",
  PLAN_UPGRADED = "PLAN_UPGRADED",
  PLAN_DOWNGRADED = "PLAN_DOWNGRADED",
  INVOICE_CREATED = "INVOICE_CREATED",
}