import { Worker } from 'bullmq';
import redisConnectionOptions from '../../../../config/redis';
import { TRANSLATION_QUEUE_NAME } from './translation.queue';
import { createQueueLogger } from '../../../../utils/queue-logger';
import { FeedLocalization } from '../../../../models/feed-localization.model';
import { FeedVersion } from '../../../../models/feed-version.model';
import { FeedAuditLog } from '../../../../models/feed-audit-log.model';
import { LLMService, TransientLLMError } from '../../../llm.service';

const logger = createQueueLogger(TRANSLATION_QUEUE_NAME);

export function createTranslationWorkers(): Worker[] {
  const worker = new Worker(
    TRANSLATION_QUEUE_NAME,
    async (job) => {
      const { localizationId, feedVersionId, targetLang, selectedKeys, userId } = job.data;
      
      logger.info(`Processing translation job`, { jobId: job.id, localizationId, targetLang });

      // 1. Fetch Localization
      const localization = await FeedLocalization.findById(localizationId);
      if (!localization) {
        logger.error(`Localization not found`, { localizationId });
        throw new Error('Localization not found');
      }

      // 2. Idempotency Check
      if (localization.status === 'COMPLETED') {
        logger.info(`Localization already completed, skipping`, { localizationId });
        return { status: 'skipped' };
      }

      // 3. Update Status to PROCESSING
      localization.status = 'PROCESSING';
      localization.attempts = (localization.attempts || 0) + 1;
      localization.startedAt = new Date();
      await localization.save();

      try {
        // 4. Fetch Feed Version for Base Content
        const feedVersion = await FeedVersion.findById(feedVersionId).lean();
        if (!feedVersion) {
          throw new Error('FeedVersion not found');
        }

        // 5. Translate (LLM call)
        // Deep merge baseContent with existing localizedContent so we don't wipe out existing translations
        const mergeDeep = (target: any, source: any, currentPath = '') => {
          if (!source) return target;
          for (const key in source) {
            const path = currentPath ? `${currentPath}.${key}` : key;
            const wildcardPath = path.replace(/\.\d+/g, '.*');
            
            const isSelected = selectedKeys && selectedKeys.length > 0 
              ? selectedKeys.some((sk: string) => wildcardPath === sk || wildcardPath.startsWith(sk + '.'))
              : true;

            if (source[key] !== null && typeof source[key] === 'object' && target[key]) {
              mergeDeep(target[key], source[key], path);
            } else {
              // If it's NOT selected for translation, restore the old French translation
              // If it IS selected, we keep the target (English) value so the LLM can translate the new English text
              if (!isSelected) {
                target[key] = source[key];
              }
            }
          }
          return target;
        };
        const baseClone = JSON.parse(JSON.stringify(feedVersion.baseContent));
        const hybridContent = mergeDeep(baseClone, localization.localizedContent || {});
        
        const translatedContent = await LLMService.mockTranslate(hybridContent, targetLang, selectedKeys);

        // 6. Success: Update MongoDB
        localization.status = 'COMPLETED';
        localization.localizedContent = translatedContent;
        localization.completedAt = new Date();
        localization.set('lastError', undefined);
        await localization.save();

        await FeedAuditLog.create({
          feedId: feedVersion.feedId,
          feedVersionId: feedVersion._id,
          userId: userId || -1,
          action: 'GENERATED_TRANSLATION',
          languageCode: targetLang,
          notes: 'Auto-generated by LLM'
        });

        logger.info(`Translation completed successfully`, { localizationId, targetLang });
        return { status: 'completed' };

      } catch (error: any) {
        // Determine if it's transient or permanent
        if (error instanceof TransientLLMError) {
          logger.warn(`Transient error during translation, will retry`, { localizationId, error: error.message });
          // Do NOT update status to FAILED here, just let BullMQ retry it
          throw error; // Let BullMQ retry
        }

        // Permanent Error (e.g. PermanentLLMError, SyntaxError)
        logger.error(`Permanent error during translation`, { localizationId, error: error.message });
        localization.status = 'FAILED';
        localization.lastError = error.message || 'Unknown permanent error';
        await localization.save();
        
        // Do NOT throw error so BullMQ considers the job "done" and stops retrying
        return { status: 'failed_permanently', reason: error.message };
      }
    },
    {
      connection: redisConnectionOptions as any,
      concurrency: 5,
    }
  );

  worker.on('failed', async (job, err) => {
    logger.error(`Job failed`, { jobId: job?.id, error: err.message });
    
    // If we've exhausted all retries and it's a transient error, mark it as FAILED in DB
    if (job && job.attemptsMade >= (job.opts.attempts || 3)) {
      try {
        const loc = await FeedLocalization.findById(job.data.localizationId);
        if (loc && loc.status !== 'FAILED' && loc.status !== 'COMPLETED') {
          loc.status = 'FAILED';
          loc.lastError = `Max retries exhausted: ${err.message}`;
          await loc.save();
          logger.error(`Max retries exhausted, marked as FAILED in DB`, { localizationId: job.data.localizationId });
        }
      } catch (dbErr) {
        logger.error(`Failed to update DB on max retries exhaustion`, { error: dbErr });
      }
    }
  });

  return [worker];
}
