export enum BillingErrorCode {
  UNKNOWN = "UNKNOWN",

  PLAN_NOT_FOUND = "PLAN_NOT_FOUND",
  INVALID_PLAN = "INVALID_PLAN",

  SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_REQUIRED = "SUBSCRIPTION_REQUIRED",
  SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED",

  TRIAL_EXPIRED = "TRIAL_EXPIRED",

  FEATURE_DISABLED = "FEATURE_DISABLED",

  QUOTA_NOT_FOUND = "QUOTA_NOT_FOUND",
  INVALID_QUOTA = "INVALID_QUOTA",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",

  USAGE_SYNC_FAILED = "USAGE_SYNC_FAILED",
  PLAN_INACTIVE = "PLAN_INACTIVE",
}